INSERT INTO customer VALUES ('C_001','James','jbutt@gmail.com','LA','New Orleans','Orleans','70116','5HQ2RzRd');
INSERT INTO customer VALUES ('C_002','Josephine','josephine_darakjy@darakjy.org','MI','Brighton','Livingston','48116','e9Wwcw4K');
INSERT INTO customer VALUES ('C_003','Art','art@venere.org','NJ','Bridgeport','Gloucester','8014','RWHyWB2C');
INSERT INTO customer VALUES ('C_004','Lenna','lpaprocki@hotmail.com','AK','Anchorage','Anchorage','99501','eMbGLrnk');
INSERT INTO customer VALUES ('C_005','Donette','donette.foller@cox.net','OH','Hamilton','Butler','45011','kvr35wrj');
INSERT INTO customer VALUES ('C_006','Simona','simona@morasca.com','OH','Ashland','Ashland','44805','LLWkgL5E');
INSERT INTO customer VALUES ('C_007','Mitsue','mitsue_tollner@yahoo.com','IL','Chicago','Cook','60632','adptYwrt');
INSERT INTO customer VALUES ('C_008','Leota','leota@hotmail.com','CA','San Jose','Santa Clara','95111','5sPJUjFX');
INSERT INTO customer VALUES ('C_009','Sage','sage_wieser@cox.net','SD','Sioux Falls','Minnehaha','57105','HKuFX2Ph');
INSERT INTO customer VALUES ('C_010','Kris','kris@gmail.com','MD','Baltimore','Baltimore City','21224','Ju7dWnBR');
INSERT INTO customer VALUES ('C_011','Minna','minna_amigon@yahoo.com','PA','Kulpsville','Montgomery','19443','fU4vWpZD');
INSERT INTO customer VALUES ('C_012','Abel','amaclead@gmail.com','NY','Middle Island','Suffolk','11953','WuGUVfAA');
INSERT INTO customer VALUES ('C_013','Kiley','kiley.caldarera@aol.com','CA','Los Angeles','Los Angeles','90034','JPsjLfbz');
INSERT INTO customer VALUES ('C_014','Graciela','gruta@cox.net','OH','Chagrin Falls','Geauga','44023','ptKZexWM');
INSERT INTO customer VALUES ('C_015','Cammy','calbares@gmail.com','TX','Laredo','Webb','78045','WTqeykvy');
INSERT INTO customer VALUES ('C_016','Mattie','mattie@aol.com','AZ','Phoenix','Maricopa','85013','zDNuU9tn');
INSERT INTO customer VALUES ('C_017','Meaghan','meaghan@hotmail.com','TN','Mc Minnville','Warren','37110','yEvELcD2');
INSERT INTO customer VALUES ('C_018','Gladys','gladys.rim@rim.org','WI','Milwaukee','Milwaukee','53207','J74XRgJ9');
INSERT INTO customer VALUES ('C_019','Yuki','yuki_whobrey@aol.com','MI','Taylor','Wayne','48180','ARsWdDYu');
INSERT INTO customer VALUES ('C_020','Fletcher','fletcher.flosi@yahoo.com','IL','Rockford','Winnebago','61109','aQ6tX6KT');
INSERT INTO customer VALUES ('C_021','Bette','bette_nicka@cox.net','PA','Aston','Delaware','19014','vrqUGyhj');
INSERT INTO customer VALUES ('C_022','Veronika','vinouye@aol.com','CA','San Jose','Santa Clara','95111','GkzJGwZ2');
INSERT INTO customer VALUES ('C_023','Willard','willard@hotmail.com','TX','Irving','Dallas','75062','h5vSTq89');
INSERT INTO customer VALUES ('C_024','Maryann','mroyster@royster.com','NY','Albany','Albany','12204','jHubKtub');
INSERT INTO customer VALUES ('C_025','Alisha','alisha@slusarski.com','NJ','Middlesex','Middlesex','8846','YVcCGmnt');
INSERT INTO customer VALUES ('C_026','Allene','allene_iturbide@cox.net','WI','Stevens Point','Portage','54481','pk5kqvTE');
INSERT INTO customer VALUES ('C_027','Chanel','chanel.caudy@caudy.org','KS','Shawnee','Johnson','66218','JaGaEDqz');
INSERT INTO customer VALUES ('C_028','Ezekiel','ezekiel@chui.com','MD','Easton','Talbot','21601','8w3HQG9Y');
INSERT INTO customer VALUES ('C_029','Willow','wkusko@yahoo.com','NY','New York','New York','10011','nCavyzj2');
INSERT INTO customer VALUES ('C_030','Bernardo','bfigeroa@aol.com','TX','Conroe','Montgomery','77301','P5frhjqj');
